# Andrew Pennington - 05/07/2021
---
- name: "Display a secret"
  hosts: "all"
  become: true      

  tasks:
    # Encrypt a file using:  ansible-vault encrypt <path/to/file>
    - name: "Load variable from an encrypted file"
      include_vars:
        file: "../Secrets/api_key"

    - name: "Display the encrypted variable"
      debug:
        msg: "{{ api_key }}"

    - name: "Display the encrypted variable, but hide the log output"
      no_log: true
      debug:
        msg: "{{ api_key }}"
